import { Component, OnInit } from '@angular/core';
import { PasswordHelperService } from '../password-helper.service';

@Component({
  selector: 'app-auto-generated-panel',
  templateUrl: './auto-generated-panel.component.html',
  styleUrls: ['./auto-generated-panel.component.scss']
})
export class AutoGeneratedPanelComponent implements OnInit {

  panelArray = [
    {icon:'default', text: 'default1', title: 'hello'},
    {icon:'default', text: 'default2', title: 'hello'},
    {icon:'default', text: 'default3', title: 'hello'},
    {icon:'default', text: 'default4', title: 'hello'},
    {icon:'default', text: 'default5', title: 'hello'},
    {icon:'default', text: 'default6', title: 'hello'},
    {icon:'default', text: 'default7', title: 'hello'},
    {icon:'default', text: 'default8', title: 'hello'}
  ];
  constructor(
    private passwordHelper: PasswordHelperService
  ) { }

  ngOnInit(): void {
    console.log(this.passwordHelper.makeKey(12));
  }

}
