import { ComponentFixture, TestBed } from '@angular/core/testing';

import { AutoGeneratedPanelComponent } from './auto-generated-panel.component';

describe('AutoGeneratedPanelComponent', () => {
  let component: AutoGeneratedPanelComponent;
  let fixture: ComponentFixture<AutoGeneratedPanelComponent>;

  beforeEach(async () => {
    await TestBed.configureTestingModule({
      declarations: [ AutoGeneratedPanelComponent ]
    })
    .compileComponents();
  });

  beforeEach(() => {
    fixture = TestBed.createComponent(AutoGeneratedPanelComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });
});
